### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by georoen** [pjaselin/ShinyServer_On_RaspberryPi#1]
Hey; unfortunately I have managed to messed up my installation and would like to do a fresh reinstall.  However, as I’m new to setting up servers, I’m not sure where to begin.. Do by any chance you already have an uninstall script? Thank you very much!

**Comment by pjaselin** [comment]
Hey, thanks for reaching out and I apologize for the delay! I think I was in your shoes a while back and I recall trying to delete every instance of shiny-server on the Pi. Although I don't have my Pi on hand, I would imagine something like sudo apt-get remove shiny-server might work, or even just recompiling the package might resolve it. Let me know if that helps at all! I might be able to look at writing an uninstall script for sure, but I'd be curious to understand why it's not working now.
