### ISSUE TITLE
node install checksum failure

### ISSUE THREAD

**Issue by Melonbob** [pjaselin/ShinyServer_On_RaspberryPi#2]
It would be good to put a comment in 'Stable_RPiShinyServer.sh'  regarding how to modify the patched 'install-node.sh' to update the NODE_SHA256 variable for newer versions.

To get the current checksums to modify the NODE_SHA256 variable, see the Verifying Binaries section in [here](https://github.com/nodejs/node#verifying-binaries)

**Comment by pjaselin** [comment]
Hi @Melonbob, thanks for raising this issue and apologies for my delay in responding! Given that we know the node version from the .nvmrc file in shiny-server/, I'm thinking I might just use that, get the right line from https://nodejs.org/dist/vx.y.z/SHASUMS256.txt and then update the 'install-node.sh' file accordingly. I really should have done that awhile ago but that would avoid requiring this to be continually updated provided the shiny-server repo structure is preserved.
