### ISSUE TITLE
git is missing in StableInstall_RPiShinyServer.sh dependencies

### ISSUE THREAD

**Issue by dimpfelmoser** [pjaselin/ShinyServer_On_RaspberryPi#4]
I ran StableInstall_RPiShinyServer.sh on a RPi4 with Raspbian Buster.
The first time it failed because git was missing.
After manuall installing git it worked.

Thanks for the script!

**Comment by pjaselin** [comment]
Hi @dimpfelmoser, thanks for letting me know and glad this was of use to you (and is still working)! I guess it shouldn't assume git is installed by default so I can fix that.
